#!/usr/bin/env bash
# Regenerate queries/iml.scm from Topiary's upstream OCaml query plus iml-extra.scm.
#
# Usage: ./update-queries.sh [topiary-tag]   (default: v0.7.3)
set -euo pipefail

TAG="${1:-v0.7.3}"
HERE="$(cd "$(dirname "$0")" && pwd)"
URL="https://raw.githubusercontent.com/tweag/topiary/${TAG}/topiary-queries/queries/ocaml.scm"
OUT="${HERE}/queries/iml.scm"

upstream="$(curl -fsSL "${URL}")"

{
  echo "; GENERATED by update-queries.sh from Topiary ${TAG}:"
  echo ";   ${URL}"
  echo "; Do not edit by hand: change iml-extra.scm or the adaptations below, then rerun."
  echo ";"
  echo "; The OCaml rules below are from Topiary and are used under its licence"
  echo "; (also in LICENSE-topiary):"
  echo ";"
  sed 's/^/; /; s/ $//' "${HERE}/LICENSE-topiary"
  echo
  # The IML grammar is forked from a newer tree-sitter-ocaml than the one Topiary
  # pins: `product_expression` became `tuple_expression`, and `typed_label` is gone.
  printf '%s\n' "${upstream}" | python3 -c '
import sys
q = sys.stdin.read()
typed_label = "(typed_label\n  \":\" @append_spaced_softline\n)\n"
assert typed_label in q, "typed_label rule not found; check the upstream query"
q = q.replace(typed_label, "").replace("product_expression", "tuple_expression")
sys.stdout.write(q)
'
  cat "${HERE}/iml-extra.scm"
} > "${OUT}"

echo "Wrote ${OUT}"
