#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.10"
# dependencies = []
# ///
"""Regenerate queries/iml.scm from Topiary's upstream OCaml query plus iml-extra.scm.

    queries/iml.scm = licence header + adapted upstream ocaml.scm + iml-extra.scm

Usage: ./update-queries.py [topiary-tag]   (default: v0.7.3)

Each adaptation names the exact upstream text it expects, and the script fails if that text is
missing, so an upstream change can't silently drop one. To add an adaptation, append to RENAMES
or PATCHES.
"""

import sys
import urllib.request
from dataclasses import dataclass
from pathlib import Path

DEFAULT_TAG = "v0.7.3"
HERE = Path(__file__).resolve().parent
OUT = HERE / "queries" / "iml.scm"


@dataclass
class Patch:
    why: str
    old: str  # exact upstream text, expected exactly once
    new: str


# Node-type renames
# =================
#
# The IML grammar is forked from a newer tree-sitter-ocaml than the one Topiary pins.

RENAMES = {
    "product_expression": "tuple_expression",
}


# Rule patches
# ============

PATCHES = [
    Patch(
        why="`typed_label` no longer exists in the newer tree-sitter-ocaml",
        old="""\
(typed_label
  ":" @append_spaced_softline
)
""",
        new="",
    ),
    # Upstream ends the let-binding indent after its last child (the trailing `.` anchor).
    # When an item attribute follows the body (`let f x = ... [@@measure ...]`), the attribute
    # is that last child and gets indented. Ending the indent after `body:` instead puts the
    # attribute back at the column of `let`, as for `theorem`.
    Patch(
        why="end the let-binding indent after the body, not after item attributes",
        old="""\
  "="
  (_
    ; any node that doesn't add its own indentation
    .
    [
      "fun" ; fun_expression
      "function" ; function_expression
      "[" ; list_expression
      "[|" ; array_expression
      "{" ; record_expression. Unfortunately this also captures quoted strings
      "(" ; parenthesized_expression. Unfortunately this also captures unit
    ]? @do_nothing
  ) @append_indent_end
  .
)
""",
        new="""\
  "="
  body: (_
    ; any node that doesn't add its own indentation
    .
    [
      "fun" ; fun_expression
      "function" ; function_expression
      "[" ; list_expression
      "[|" ; array_expression
      "{" ; record_expression. Unfortunately this also captures quoted strings
      "(" ; parenthesized_expression. Unfortunately this also captures unit
    ]? @do_nothing
  ) @append_indent_end
)
""",
    ),
    Patch(
        why="same as above, for the quoted-string and unit special case",
        old="""\
  "="
  [
    (quoted_string)
    (unit)
  ] @append_indent_end
  .
)
""",
        new="""\
  "="
  body: [
    (quoted_string)
    (unit)
  ] @append_indent_end
)
""",
    ),
]


# Main
# ====


def fail(message: str) -> None:
    sys.exit(f"update-queries.py: {message}; check the upstream query")


def adapt(query: str) -> str:
    for old, new in RENAMES.items():
        if old not in query:
            fail(f"node type `{old}` not found")
        query = query.replace(old, new)
    for patch in PATCHES:
        count = query.count(patch.old)
        if count != 1:
            fail(f"expected 1 match, found {count}, for patch: {patch.why}")
        query = query.replace(patch.old, patch.new)
    return query


def header(tag: str, url: str) -> str:
    licence = (HERE / "LICENSE-topiary").read_text().splitlines()
    lines = [
        f"GENERATED by update-queries.py from Topiary {tag}:",
        f"  {url}",
        "Do not edit by hand: change iml-extra.scm or the adaptations in update-queries.py,",
        "then rerun.",
        "",
        "The OCaml rules below are from Topiary and are used under its licence",
        "(also in LICENSE-topiary):",
        "",
        *licence,
    ]
    return "".join(f"; {line}".rstrip() + "\n" for line in lines) + "\n"


def main() -> None:
    tag = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_TAG
    url = f"https://raw.githubusercontent.com/tweag/topiary/{tag}/topiary-queries/queries/ocaml.scm"
    with urllib.request.urlopen(url) as response:
        upstream = response.read().decode()
    # Build everything before writing, so a failure leaves the existing query untouched.
    query = (
        header(tag, url)
        + adapt(upstream).rstrip("\n")
        + "\n"
        + (HERE / "iml-extra.scm").read_text()
    )
    OUT.write_text(query)
    print(f"Wrote {OUT}")


if __name__ == "__main__":
    main()
